name: via_mallorca
description: An open source app for tracking Mallorca Transit.
publish_to: "none"
version: 1.6.0+11

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  mallorca_transit_services: ^1.2.1
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_local_notifications: ^19.2.1
  flutter_map: ^8.2.2
  flutter_map_marker_cluster: ^8.2.2
  latlong2: ^0.9.1
  permission_handler: ^12.0.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  skeletonizer: ^2.0.1
  syncfusion_flutter_pdfviewer: ^31.2.18
  timezone: ^0.10.0
  url_launcher: ^6.2.5
  locale_names: ^1.1.1
  flutter_map_location_marker: ^10.1.0
  geolocator: ^14.0.2
  connectivity_plus: ^7.0.0
  flutter_map_animations: ^0.9.0
  timelines:
    git:
      url: https://github.com/quqo-dev/timelines.git
      ref: main
  material_design_icons_flutter: ^7.0.7296
  flutter_map_tile_caching: ^10.1.1
  path_provider: ^2.1.5
  flutter_map_cancellable_tile_provider: ^3.0.2
  numberpicker: ^2.1.2
  web_socket_channel: ^3.0.3
  quick_actions: ^1.1.0
  hooks_riverpod: ^3.0.3
  flutter_hooks: ^0.21.3+1

dependency_overrides:
  intl: ^0.20.2
  flutter_compass:
    git:
      url: https://github.com/PikPakPik/flutter_compass.git
      ref: master

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
